name: Cypress Tests - Complete Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'

      - name: Install dependencies
        run: npm install
        working-directory: ./teste

      - name: Fix Cypress permissions
        run: chmod -R 755 ./teste/node_modules/.bin

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./teste
